admins/urls.py
from django.urls import path

from admins.views import *

app_name = 'admins'

urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admins_users_read'),
    path('users-create/', UserCreateView.as_view(), name='admins_users_create'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admins_users_delete'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admins_users_update'),
    path('products/', admin_products_read, name='admins_products_read'),
    path('products-create/', admin_products_create, name='admins_products_create'),
    path('products-delete/<int:pk>/', admin_products_delete, name='admins_products_delete'),
    path('products-update/<int:pk>/', admin_products_update, name='admins_products_update'),
    path('categories/', admin_categories_read, name='admins_categories_read'),
    path('categories-create/', admin_categories_create, name='admins_categories_create'),
    path('categories-delete/<int:pk>/', admin_categories_delete, name='admins_categories_delete'),
    path('categories-update/<int:pk>/', admin_categories_update, name='admins_categories_update'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('admins/', include('admins.urls', namespace='admins'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, UserRegistrationView, UserProfileView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
]

admins/templates/categories/admin-categories-create.html
{% extends "admins/base.html" %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Создание категории</h1>
            <form action="{% url "admins:admins_categories_create" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
               <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                            {{ form.name }}
                        </div>
                    </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

admins/templates/categories/admin-categories-read.html
{% extends "admins/base.html" %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Наименование</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Наименование</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for category in categories %}
                                <tr>
                                    <td>
                                        <a href="{% url "admins:admins_categories_update" category.id %}"
                                           style="color: dodgerblue">
                                            {{ category.name }}
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        {% if category.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url "admins:admins_categories_create" %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/categories/admin-categories-update-delete.html
{% extends "admins/base.html" %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование категории | {{ selected_category.name }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admins_categories_update' selected_category.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <a class="btn btn-danger btn-block"
                           href="{% url "admins:admins_categories_delete" selected_category.id %}">
                            Удалить
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}