admins/urls.py
from django.urls import path

from admins.views import *

app_name = 'admins'

urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admins_users_read'),
    path('users-create/', UserCreateView.as_view(), name='admins_users_create'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admins_users_delete'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admins_users_update'),
    path('products/', admin_products_read, name='admins_products_read'),
    path('products-create/', admin_products_create, name='admins_products_create'),
    path('products-delete/<int:pk>/', admin_products_delete, name='admins_products_delete'),
    path('products-update/<int:pk>/', admin_products_update, name='admins_products_update'),
    path('categories/', admin_categories_read, name='admins_categories_read'),
    path('categories-create/', admin_categories_create, name='admins_categories_create'),
    path('categories-delete/<int:pk>/', admin_categories_delete, name='admins_categories_delete'),
    path('categories-update/<int:pk>/', admin_categories_update, name='admins_categories_update'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('admins/', include('admins.urls', namespace='admins'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import ProductsListView

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='home_page'),
    path('<int:category_id>/', ProductsListView.as_view(), name='product'),
    path('page/<int:page>/', ProductsListView.as_view(), name='page'),
]

users/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, UserRegistrationView, UserProfileView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
]

products/models.py
from django.db import models


class ProductCategories(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name="Категория")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Категория товара"
        verbose_name_plural = "Категории товаров"

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=256, verbose_name="Наименование")
    image = models.ImageField(upload_to="products_images", blank=True, verbose_name="Фото")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    category = models.ForeignKey(ProductCategories, on_delete=models.CASCADE, verbose_name="Категория")
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render
import datetime
from products.models import ProductCategories, Products
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from common.views import CommonContextMixin


class IndexView(CommonContextMixin, TemplateView):
    template_name = 'index.html'
    title = 'GeekShop'


# def index(request):
#     context = {
#         "date_time": datetime.datetime.now(),
#         "title": "GeekShop",
#         "is_promotion": 1,
#         "promotion_text": "Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям."
#     }
#     return render(request, "index.html", context)


class ProductsListView(CommonContextMixin, ListView):
    model = Products
    template_name = 'products.html'
    paginate_by = 3
    title = 'GeekShop - Каталог'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['categories'] = ProductCategories.objects.all()
        return context


# def products(request, category_id=None, page=1):
#     context = {'title': 'GeekShop - Товары', 'categories': ProductCategories.objects.all()}
#     if category_id:
#         _products = Products.objects.filter(category_id=category_id)
#     else:
#         _products = Products.objects.all()
#     paginator = Paginator(_products, 3)
#     try:
#         products_paginator = paginator.page(page)
#     except PageNotAnInteger:
#         products_paginator = paginator.page(1)
#     except EmptyPage:
#         products_paginator = paginator.page(paginator.num_pages)
#     context['products'] = products_paginator
#     return render(request, "products.html", context)

admins/templates/products/admin-products-create.html
{% extends "admins/base.html" %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Создание продукта</h1>
            <form action="{% url "admins:admins_products_create" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
               <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Ноименование</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                Выберите изображение
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Колличество</label>
                        {{ form.quantity }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                        {{ form.price }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                        {{ form.category }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

admins/templates/products/admin-products-read.html
{% extends "admins/base.html" %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Продукты</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Продукты
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Наименование</th>
                                <th>Описание</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Категория</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Наименование</th>
                                <th>Описание</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Категория</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for product in products %}
                                <tr>
                                    <td>
                                        <a href="{% url "admins:admins_products_update" product.id %}" style="color: dodgerblue">
                                            {{ product.name }}
                                        </a>
                                    </td>
                                    <td>{{ product.description }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.category }}</td>
                                    <td class="text-center">
                                        {% if product.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url "admins:admins_products_create" %}">
                        <button class="btn btn-success">Создать продукт</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/products/admin-products-update-delete.html
{% extends "admins/base.html" %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование продукта | {{ selected_product.name }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admins_products_update' selected_product.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                    Выберите изображение
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                            {{ form.price }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                            {{ form.quantity }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <a class="btn btn-danger btn-block"
                           href="{% url "admins:admins_products_delete" selected_product.id %}">
                            Удалить
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}